// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  NewOneStmt1 = 3,
  NewOne1 = 4,
  NumberStmt = 5,
  Number = 6,
  OperatorStmt = 7,
  Operator = 8,
  IdentifierStmt = 9,
  Identifier = 10,
  ParensStmt = 11,
  Parens = 12
