// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!dQVQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cg'#CgOOQO'#Ci'#CiOOQO'#C^'#C^OOQO'#Ck'#CkQVQPOOOOQO-E6i-E6i",
  stateData: "k~ObOS~OSPOUQOWROYSO[TO^UO~O",
  goto: "o`PPaePePePePePePiTWOXTVOXQXORYX",
  nodeNames: "⚠ Program Statement NewOneStmt1 NewOne1 NewOneStmt2 NewOne2 NumberStmt Number OperatorStmt Operator IdentifierStmt Identifier ParensStmt Parens",
  maxTerm: 18,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "1q~Rrqr#]xy#byz#bz{#]{|#]}!O#g!P!Q#]![!]#o!]!^#]!^!_#]!_!`#]!`!a#]!c!d#u!d!e$W!e!f$^!f!g%[!h!i%n!i!j&Q!k!l&d!n!o']!q!r'o!u!v(X!v!w(q!}#O)T#T#U-Y#U#V-f#V#W-l#W#X.[#Y#Z.n#Z#[/Q#]#^/d#c#d0]#g#h0u#h#i1_~#bOY~~#gO^~~#lPY~!`!a#]~#rP![!]#]~#xP!n!o#{~$OP!n!o$R~$WOS~~$ZP!{!|$R~$aQ!t!u$g!u!v%P~$jP!g!h$m~$pP!c!d$s~$vP!v!w$y~$|P!g!h$R~%SP!x!y%V~%[OU~~%_P!t!u%b~%eP!q!r%h~%kP!r!s$R~%qP!t!u%t~%wP!q!r%z~%}P!o!p$R~&TP!t!u&W~&ZP!q!r&^~&aP!w!x%h~&gP!p!q&j~&mQ!u!v&s!v!w'V~&vP!g!h&y~&|P!t!u'P~'SP!v!w$R~'YP!q!r$R~'`P!q!r'c~'fP!c!d'i~'lP!f!g%V~'rP!t!u'u~'xP!f!g'{~(OP!g!h(R~(UP!t!u$R~([P!g!h(_~(bP!n!o(e~(hP!g!h(k~(nP!e!f'P~(tP!c!d(w~(zP!d!e(}~)QP!n!o$y~)WRpq)a!Q!R*U#T#U*s~)dPXY)g~)jP]^)m~)pPYZ)s~)vP#P#Q)y~)|P{|*P~*UOb~~*XP}!O*[~*_P!Z![*b~*eP#P#Q*h~*kP{|*n~*sOW~~*vP}!O*y~*|P#n#o+P~+SP!c!d+V~+YP}!O+]~+`P!|!}+c~+fP#P#Q+i~+lP!}#O+o~+rP#T#U+u~+xP}!O+{~,OP#n#o,R~,UP!c!d,X~,[P}!O,_~,bP!|!},e~,hP!Q!R,k~,nP}!O,q~,tP!Z![,w~,zP#P#Q,}~-QPz{-T~-YO[~~-]P#`#a-`~-cP#`#a$R~-iP#m#n$R~-oP#f#g-r~-uP#X#Y-x~-{P#T#U.O~.RP#h#i.U~.XP#X#Y$R~._P#f#g.b~.eP#c#d.h~.kP#d#e$R~.qP#f#g.t~.wP#c#d.z~.}P#a#b$R~/TP#f#g/W~/ZP#c#d/^~/aP#i#j.h~/gP#b#c/j~/mQ#g#h/s#h#i0V~/vP#X#Y/y~/|P#f#g0P~0SP#h#i$R~0YP#c#d$R~0`P#f#g0c~0fP#W#X0i~0lP#X#Y0o~0rP#f#g$R~0xP#X#Y0{~1OP#`#a1R~1UP#X#Y1X~1[P#V#W0P~1bP#T#U1e~1hP#U#V1k~1nP#`#a.U",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
