// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QVQPOOOOQO'#C_'#C_OOQO'#Ca'#CaOOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cg'#CgOOQO'#C^'#C^OOQO'#Ci'#CiQVQPOOOOQO-E6g-E6g",
  stateData: "h~O`OS~OSPOUQOWROYSO[TO~O",
  goto: "m^PP_cPcPcPcPcPgTVOWTUOWQWORXW",
  nodeNames: "⚠ Program Statement NewOneStmt1 NewOne1 NumberStmt Number OperatorStmt Operator IdentifierStmt Identifier ParensStmt Parens",
  maxTerm: 16,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: ".f~Rkqr!vxy!{yz!{z{!v{|!v}!O#Q!P!Q!v![!]#Y!]!^!v!^!_!v!_!`!v!`!a!v!c!d#`!e!f#q!f!g$a!h!i$s!k!l%V!u!v&O!v!w&h!}#O&z#T#U+P#V#W+]#W#X+{#Y#Z,_#]#^,q#g#h-j#h#i.S~!{OW~~#QO[~~#VPW~!`!a!v~#]P![!]!v~#cP!n!o#f~#iP!n!o#l~#qOS~~#tP!t!u#w~#zP!g!h#}~$QP!c!d$T~$WP!v!w$Z~$^P!g!h#l~$dP!t!u$g~$jP!q!r$m~$pP!r!s#l~$vP!t!u$y~$|P!q!r%P~%SP!o!p#l~%YP!p!q%]~%`Q!u!v%f!v!w%x~%iP!g!h%l~%oP!t!u%r~%uP!v!w#l~%{P!q!r#l~&RP!g!h&U~&XP!n!o&[~&_P!g!h&b~&eP!e!f%r~&kP!c!d&n~&qP!d!e&t~&wP!n!o$Z~&}Rpq'W!Q!R'{#T#U(j~'ZPXY'^~'aP]^'d~'gPYZ'j~'mP#P#Q'p~'sP{|'v~'{O`~~(OP}!O(R~(UP!Z![(X~([P#P#Q(_~(bP{|(e~(jOU~~(mP}!O(p~(sP#n#o(v~(yP!c!d(|~)PP}!O)S~)VP!|!})Y~)]P#P#Q)`~)cP!}#O)f~)iP#T#U)l~)oP}!O)r~)uP#n#o)x~){P!c!d*O~*RP}!O*U~*XP!|!}*[~*_P!Q!R*b~*eP}!O*h~*kP!Z![*n~*qP#P#Q*t~*wPz{*z~+POY~~+SP#`#a+V~+YP#`#a#l~+`P#f#g+c~+fP#X#Y+i~+lP#T#U+o~+rP#h#i+u~+xP#X#Y#l~,OP#f#g,R~,UP#c#d,X~,[P#d#e#l~,bP#f#g,e~,hP#c#d,k~,nP#a#b#l~,tP#b#c,w~,zQ#g#h-Q#h#i-d~-TP#X#Y-W~-ZP#f#g-^~-aP#h#i#l~-gP#c#d#l~-mP#X#Y-p~-sP#`#a-v~-yP#X#Y-|~.PP#V#W-^~.VP#T#U.Y~.]P#U#V.`~.cP#`#a+u",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
