// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Statement = 2,
  NewOneStmt1 = 3,
  NewOne1 = 4,
  NewOneStmt2 = 5,
  NewOne2 = 6,
  NumberStmt = 7,
  Number = 8,
  OperatorStmt = 9,
  Operator = 10,
  IdentifierStmt = 11,
  Identifier = 12,
  ParensStmt = 13,
  Parens = 14
